from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit

class NewStudentForm(forms.Form):
    name = forms.CharField(max_length=35, widget=forms.TextInput(attrs={'placeholder': 'Ron Weasley'}))
    netid = forms.CharField(max_length=10, widget=forms.TextInput(attrs={'placeholder': 'rw447'}))
    # hometown = forms.CharField(max_length=35, widget=forms.TextInput(attrs={'placeholder': 'Dallas, Texas'}))
    YEAR = (
        ('Freshman', 'Freshman'),
        # ('Freshman Spring Transfer', 'Freshman Spring Transfer'),
        ('Sophomore', 'Sophomore'),
        ('Sophomore Transfer', 'Sophomore Transfer'),
        # ('Junior', 'Junior'),
        ('Junior Transfer', 'Junior Transfer'),
        # ('Senior', 'Senior'),
    )
    year = forms.ChoiceField(label=("Class Year"),
        choices=YEAR, widget=forms.Select(),)
    
    SURVEY = (
    ('Clubfest','Clubfest'),
    ('Advertising','Advertising'),
    ('Another organization','Another organization'),
    ('Social Media','Social Media'),
    ('Word of mouth','Word of mouth'),
    )
    survey = forms.MultipleChoiceField(label=("How did you hear about Let’s Get Coffee?"),
        choices=SURVEY, widget=forms.CheckboxSelectMultiple(), required=False)
 
    HEARD = (
        ('None','None'),
        ('Alternative Breaks','Alternative Breaks'),
        ('APO','APO'),
        ('BEARS','BEARS'),
        ('CAPSU','CAPSU'),
        ('CIAS','CIAS'),
        ('Cornell Dems','Cornell Dems'),
        ('Cornell Political Union','Cornell Political Union'),
        ('CornellRadio.com','CornellRadio.com'),
        ('CUABS','CUABS'),
        ('DSP','DSP'),
        ('ECO','ECO'),
        ('Forte','Forte'),
        ('Haven','Haven'),
        ('Hillel','Hillel'),
        ('IFC','IFC'),
        ('ISU','ISU'),
        ('KAPi','KAPi'),
        ('MGLC','MGLC'),
        ('OSC','OSC'),
        ('PHC','PHC'),
        ('Phi Delta Epsilon','Phi Delta Epsilon'),
        ('Slope Media','Slope Media'),
        ('Speech & Debate','Speech & Debate'),
        ('Tatkon Center','Tatkon Center'), 
    )
    heard = forms.ChoiceField(label=("If you heard about us from one of our partnering campus organizations, specify below:"),
        choices=HEARD, widget=forms.Select(), required=False)

    PARTICIPATED = (
        ('No','No'),
        ('Yes','Yes'),
    )
    participated = forms.ChoiceField(label=("Have you participated in Let's Get Coffee before?"),
        choices=PARTICIPATED, widget=forms.Select(),)

    SCHOOL = (
        ('Agriculture & Life Sciences', 'Agriculture & Life Sciences'),
        ('Arts & Sciences', 'Arts & Sciences'),
        ('Architecture, Art & Planning','Architecture, Art & Planning'),
        ('Engineering','Engineering'),
        ('Hotel Administration','Hotel Administration'),
        ('Human Ecology','Human Ecology'),
        ('Industrial & Labor Relations','Industrial & Labor Relations'),
    )
    school = forms.ChoiceField(label=("College"),
        choices=SCHOOL, widget=forms.Select(),)
    MAJOR = (
        #First entry is an abbreviation, second is how it appears on the site
        ('Africana Studies','Africana Studies'),
        ('Agricultural Sciences','Agricultural Sciences'),
        ('American Studies','American Studies'),
        ('Animal Science','Animal Science'),
        ('Anthropology','Anthropology'),
        ('Applied Economics and Management','Applied Economics and Management'),
        ('Archaeology','Archaeology'),
        ('Architecture','Architecture'),
        ('Asian Studies','Asian Studies'),
        ('Astronomy','Astronomy'),
        ('Atmospheric Science','Atmospheric Science'),
        ('Biological Engineering','Biological Engineering'),
        ('Biological Sciences','Biological Sciences'),
        ('Biology and Society','Biology and Society'),
        ('Biometry and Statistics','Biometry and Statistics'),
        ('Chemical Engineering','Chemical Engineering'),
        ('Chemistry and Chemical Biology','Chemistry and Chemical Biology'),
        ('China and Asia-Pacific Studies','China and Asia-Pacific Studies'),
        ('Civil Engineering','Civil Engineering'),
        ('Classics','Classics'),
        ('College Scholar','College Scholar'),
        ('Communication','Communication'),
        ('Comparative Literature','Comparative Literature'),
        ('Computer Science','Computer Science'),
        ('Design and Environmental Analysis','Design and Environmental Analysis'),
        ('Development Sociology','Development Sociology'),
        ('Economics','Economics'),
        ('Electrical and Computer Engineering','Electrical and Computer Engineering'),
        ('Engineering Physics','Engineering Physics'),
        ('English','English'),
        ('Entomology','Entomology'),
        ('Environmental and Sustainable Sciences','Environmental and Sustainable Sciences'),
        ('Environmental Engineering','Environmental Engineering'),
        ('Feminist, Gender and Sexuality Studies','Feminist, Gender and Sexuality Studies'),
        ('Fiber Science and Apparel Design','Fiber Science and Apparel Design'),
        ('Fine Arts','Fine Arts'),
        ('Food Science','Food Science'),
        ('French','French'),
        ('German Studies','German Studies'),
        ('Global and Public Health Sciences','Global and Public Health Sciences'),
        ('Government','Government'),
        ('History','History'),
        ('History of Architecture','History of Architecture'),
        ('History of Art','History of Art'),
        ('Hotel Administration','Hotel Administration'),
        ('Human Biology, Health and Society','Human Biology, Health and Society'),
        ('Human Development','Human Development'),
        ('Industrial and Labor Relations','Industrial and Labor Relations'),
        ('Information Science','Information Science'),
        ('Information Science Systems and Technology','Information Science, Systems and Technology'),
        ('Interdisciplinary Studies','Interdisciplinary Studies'),
        ('International Agriculture and Rural Development','International Agriculture and Rural Development'),
        ('Italian','Italian'),
        ('Landscape Architecture','Landscape Architecture'),
        ('Linguistics','Linguistics'),
        ('Materials Science and Engineering','Materials Science and Engineering'),
        ('Mathematics','Mathematics'),
        ('Mechanical Engineering','Mechanical Engineering'),
        ('Music','Music'),
        ('Near Eastern Studies','Near Eastern Studies'),
        ('Nutritional Sciences','Nutritional Sciences'),
        ('Operations Research and Engineering','Operations Research and Engineering'),
        ('Performing and Media Arts','Performing and Media Arts'),
        ('Philosophy','Philosophy'),
        ('Physics','Physics'),
        ('Plant Sciences','Plant Sciences'),
        ('Policy Analysis and Management','Policy Analysis and Management'),
        ('Psychology','Psychology'),
        ('Religious Studies','Religious Studies'),
        ('Science and Technology Studies','Science and Technology Studies'),
        ('Science of Earth Systems','Science of Earth Systems'),
        ('Sociology','Sociology'),
        ('Spanish','Spanish'),
        ('Statistics','Statistics'),
        ('Urban and Regional Planning','Urban and Regional Planning'),
        ('Viticulture and Enology','Viticulture and Enology'),
    )
    major = forms.ChoiceField(label=("Major"),
        choices=MAJOR, widget=forms.Select(),)

    MINOR = (
        #First entry is an abbreviation, second is how it appears on the site
        #THIS IS ACTUALLY SECOND MAJOR, SHOULD BE THE EXACT SAME AS THE LIST ABOVE
        ('None', 'None'),
        ('Africana Studies','Africana Studies'),
        ('Agricultural Sciences','Agricultural Sciences'),
        ('American Studies','American Studies'),
        ('Animal Science','Animal Science'),
        ('Anthropology','Anthropology'),
        ('Applied Economics and Management','Applied Economics and Management'),
        ('Archaeology','Archaeology'),
        ('Architecture','Architecture'),
        ('Asian Studies','Asian Studies'),
        ('Astronomy','Astronomy'),
        ('Atmospheric Science','Atmospheric Science'),
        ('Biological Engineering','Biological Engineering'),
        ('Biological Sciences','Biological Sciences'),
        ('Biology and Society','Biology and Society'),
        ('Biometry and Statistics','Biometry and Statistics'),
        ('Biomedical Engineering', 'Biomedical Engineering'),
        ('Chemical Engineering','Chemical Engineering'),
        ('Chemistry and Chemical Biology','Chemistry and Chemical Biology'),
        ('China and Asia-Pacific Studies','China and Asia-Pacific Studies'),
        ('Civil Engineering','Civil Engineering'),
        ('Classics','Classics'),
        ('College Scholar','College Scholar'),
        ('Communication','Communication'),
        ('Comparative Literature','Comparative Literature'),
        ('Computer Science','Computer Science'),
        ('Design and Environmental Analysis','Design and Environmental Analysis'),
        ('Development Sociology','Development Sociology'),
        ('Economics','Economics'),
        ('Electrical and Computer Engineering','Electrical and Computer Engineering'),
        ('Engineering Physics','Engineering Physics'),
        ('English','English'),
        ('Entomology','Entomology'),
        ('Environmental and Sustainable Sciences','Environmental and Sustainable Sciences'),
        ('Environmental Engineering','Environmental Engineering'),
        ('Feminist, Gender and Sexuality Studies','Feminist, Gender and Sexuality Studies'),
        ('Fiber Science and Apparel Design','Fiber Science and Apparel Design'),
        ('Fine Arts','Fine Arts'),
        ('Food Science','Food Science'),
        ('French','French'),
        ('German Studies','German Studies'),
        ('Global and Public Health Sciences','Global and Public Health Sciences'),
        ('Government','Government'),
        ('History','History'),
        ('History of Architecture','History of Architecture'),
        ('History of Art','History of Art'),
        ('Hotel Administration','Hotel Administration'),
        ('Human Biology, Health and Society','Human Biology, Health and Society'),
        ('Human Development','Human Development'),
        ('Industrial and Labor Relations','Industrial and Labor Relations'),
        ('Information Science','Information Science'),
        ('Information Science Systems and Technology','Information Science, Systems and Technology'),
        ('Interdisciplinary Studies','Interdisciplinary Studies'),
        ('International Agriculture and Rural Development','International Agriculture and Rural Development'),
        ('Italian','Italian'),
        ('Landscape Architecture','Landscape Architecture'),
        ('Linguistics','Linguistics'),
        ('Materials Science and Engineering','Materials Science and Engineering'),
        ('Mathematics','Mathematics'),
        ('Mechanical Engineering','Mechanical Engineering'),
        ('Music','Music'),
        ('Near Eastern Studies','Near Eastern Studies'),
        ('Nutritional Sciences','Nutritional Sciences'),
        ('Operations Research and Engineering','Operations Research and Engineering'),
        ('Performing and Media Arts','Performing and Media Arts'),
        ('Philosophy','Philosophy'),
        ('Physics','Physics'),
        ('Plant Sciences','Plant Sciences'),
        ('Policy Analysis and Management','Policy Analysis and Management'),
        ('Psychology','Psychology'),
        ('Religious Studies','Religious Studies'),
        ('Science and Technology Studies','Science and Technology Studies'),
        ('Science of Earth Systems','Science of Earth Systems'),
        ('Sociology','Sociology'),
        ('Spanish','Spanish'),
        ('Statistics','Statistics'),
        ('Urban and Regional Planning','Urban and Regional Planning'),
        ('Viticulture and Enology','Viticulture and Enology'),
    )
    minor = forms.ChoiceField(label=("Second Major (only select a second if you are seriously considering this major)"),
        choices=MINOR, widget=forms.Select(),)

    EXTRACURRICULARS = (
        #First entry is an abbreviation, second is how it appears on the site
        ('Acapella','Acapella'),
        ('Art','Art'),
        ('Club or Intramural Sports','Club or Intramural Sports'),
        ('Comedy','Comedy'),
        ('Community Service','Community Service'),
        ('Cultural','Cultural'),
        ('Dance','Dance'),
        ('Design and Graphics','Design and Graphics'),
        ('Entrepreneurship','Entrepreneurship'),
        ('Environmental Sustainability','Environmental Sustainability'),
        ('Fashion','Fashion'),
        ('Greek Life','Greek Life'),
        ('Journalism','Journalism'),
        ('Languages','Languages'),
        ('LGBTQ','LGBTQ'),
        ('Media','Media'),
        ('Music','Music'),
        ('Outdoor Recreation','Outdoor Recreation'),
        ('Partying','Partying'),
        ('Pre-Professional Organizations','Pre-Professional Organizations'),
        ('Project Team','Project Team'),
        ('Political Activism','Political Activism'),
        ('Science Research','Science Research'),
        ('Social Science Research','Social Science Research'),
        ('Teaching/Tutoring','Teaching/Tutoring'),
        ('Travel','Travel'),
        ('Religious','Religious'),
        ('ROTC','ROTC'),
        ('Speech and Debate','Speech and Debate'),
        ('Student Government','Student Government'),
        ('Theatre','Theatre'),
        ('Varsity Sports','Varsity Sports'),
    )

    extracurriculars = forms.MultipleChoiceField(label=("Select up to five activities of extracurricular interest"),
        choices=EXTRACURRICULARS, widget=forms.CheckboxSelectMultiple())

    extra_sa = forms.CharField(label=("Feel free to list any other specific extracurricular activities (125 words max)."),
        widget=forms.Textarea, max_length=638, required=False)

    CAREER = (
        #First entry is an abbreviation, second is how it appears on the site
        ('Agriculture','Agriculture'),
        ('Art/Design','Art/Design'),
        ('Biomedical Research','Biomedical Research'),
        ('Business and Finance','Business and Finance'),
        ('Computer and Technology','Computer and Technology'),
        ('Education','Education'),
        ('Engineering','Engineering'),
        ('Entertainment','Entertainment'),
        ('Graduate Study','Graduate Study'),
        ('Government','Government'),
        ('Health Professions','Health Professions'),
        ('Hospitality','Hospitality'),
        ('International Clubs','International Clubs'),
        ('International Development','International Development'),
        ('Journalism','Journalism'),
        ('Law','Law'),
        ('Management','Management'),
        ('Media Communications','Media Communications'),
        ('Military and ArmedForces','Military and Armed Forces'),
        ('Non-Profit','Non-Profit'),
        ('Public Health','Public Health'),
        ('Sales and Marketing','Sales and Marketing'),
        ('Social Science Research','Social Science Research'),
    )

    career = forms.MultipleChoiceField(label=("Select up to three prospective fields of career interest"),
        choices=CAREER, widget=forms.CheckboxSelectMultiple())

    career_sa = forms.CharField(label=("Feel free to list any other specific prospective careers (125 words max)."),
        widget=forms.Textarea, max_length=638, required=False)

    sa1 = forms.CharField(label=("What do you want to gain from this meeting with your upperclassman? (125 words max)"),
        widget=forms.Textarea(attrs={'placeholder': 'Help choosing classes, advice for careers, just a new friend, etc.'}), max_length=638)

    sa2 = forms.CharField(label=("What questions do you want to ask of your upperclassman? (125 words max)"),
        widget=forms.Textarea(attrs={'placeholder': 'How do you balance your studies and social life, keep in touch with family and friends back home, approach professors, etc.'}), max_length=638)
    sa3 = forms.CharField(label=("Tell us something interesting about yourself. (125 words max)"),
        widget=forms.Textarea(attrs={'placeholder': 'Whatever comes to mind! Don’t spend too much time on it.'}), max_length=638)

    PARTNERING = (
        #First entry is an abbreviation, second is how it appears on the site
        ('Alternative Breaks','Alternative Breaks: Promoting active citizenship and engaging students in service-learning trips over spring break'),
        ('APO','Alpha Phi Omega (APO): A student organization for community service at Cornell and in Ithaca'),
        ('BEARS','BEARS: Helping freshmen utilize campus resources and get more out of their year by matching them with an upperclassman mentor'),
        ('CAPSU','Cornell Asian Pacific Islander Student Union (CAPSU): Representing and connecting the Asian community at Cornell'),
        ('CIAS','Cornell International Affairs Society (CIAS): Discussions of international affairs and the Cornell group for Model UN'),
        ('Cornell Dems','Cornell Dems: Promoting, supporting, and engaging the Democratic Party at Cornell'),
        ('Cornell Political Union','Cornell Political Union: Bringing Democrats and Republicans together in meaningful discussion'),
        ('Cornell Radio','CornellRadio.com: An online radio station programmed by and for Cornell students'),
        ('CUABS','Cornell Undergraduate Asia Business Society (CUABS): A team of students passionate about contributing to the future of Asia'),
        ('DSP','Delta Sigma Pi: A professional business fraternity devoted to promoting competency and achievement in the field of business'),
        ('ECO','ECO (Cornell Environmental Collaborative): The umbrella organization for all environmental and sustainability clubs at Cornell'),
        ('Forte','Forte Campus at Cornell: The ultimate career connection and network for women interested in business'),
        ('Greek Life','Greek Life Tri-Council: The IFC, PHC, and MGLC comprising greek life at Cornell'),
        ('Haven','Haven: The LGBTQ+ student union at Cornell, providing community, support and education for LGBTQ+ students and allies'),
        ('Hillel','Hillel: The hub for Jewish community, religious, and cultural life for Jewish students of all backgrounds'),
        ('ISU','International Student Union (ISU): A diverse group of students promoting engagement about world cultures and issues'),
        ('KAPi','Kappa Alpha Pi: A selective pre law fraternity committed to preparing students for law school applications and a legal career'),
        ('OSC','Orientation Steering Committee (OSC): The student group responsible for organizing new student orientation'),
        ('Phi Delta Epsilon','Phi Delta Epsilon International Medical Fraternity: A top premed fraternity at Cornell'),
        ('Prepare', 'Prepare: pre-orientation program for incoming international students; an opportunity to make new friends from all over the world.'),
        ('Slope Media','Slope Media: As the Cornell multimedia powerhouse, Slope is a leader in Cornell-related media and entertainment'),
        ('Speech and Debate','Cornell Speech & Debate Society: Organizing intercollegiate speech and debate competition at Cornell'),
        ('Tatkon Center','Tatkon Center: Connecting the academic heart of Cornell with the residential center of student life on north campus')
)   

    partnering = forms.MultipleChoiceField(label=("We partner with some of the best organizations on campus. Let them know if you’re interested in what they do."),
        choices=PARTNERING, widget=forms.CheckboxSelectMultiple(), required=False)

