# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('upperclassman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('netid', models.CharField(max_length=10)),
                ('hometown', models.CharField(max_length=35)),
                ('year', models.CharField(max_length=20)),
                ('college', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=200)),
                ('minor', models.TextField()),
                ('extracurricular', models.TextField()),
                ('extra_sa', models.TextField(max_length=75, null=True)),
                ('career', models.TextField()),
                ('career_sa', models.TextField(max_length=75, null=True)),
                ('sa1', models.TextField(max_length=250, null=True)),
                ('sa2', models.TextField(max_length=250, null=True)),
                ('sa3', models.TextField(max_length=250, null=True)),
                ('survey', models.TextField()),
                ('selected', models.BooleanField(default=False)),
                ('upperclassman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upperclassman.Upperclassman')),
            ],
        ),
    ]
