# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newstudent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newstudent',
            name='hometown',
        ),
    ]
