# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newstudent', '0002_remove_newstudent_hometown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstudent',
            name='career_sa',
            field=models.TextField(max_length=638, null=True),
        ),
        migrations.AlterField(
            model_name='newstudent',
            name='extra_sa',
            field=models.TextField(max_length=638, null=True),
        ),
        migrations.AlterField(
            model_name='newstudent',
            name='sa1',
            field=models.TextField(max_length=638, null=True),
        ),
        migrations.AlterField(
            model_name='newstudent',
            name='sa2',
            field=models.TextField(max_length=638, null=True),
        ),
        migrations.AlterField(
            model_name='newstudent',
            name='sa3',
            field=models.TextField(max_length=638, null=True),
        ),
    ]
