# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newstudent', '0004_newstudent_partnering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstudent',
            name='partnering',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
