# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upperclassman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('netid', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('major1', models.CharField(max_length=200)),
                ('major2', models.CharField(max_length=200)),
                ('major3', models.CharField(max_length=200, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('survey', models.TextField()),
                ('organization', models.TextField()),
            ],
        ),
    ]
